-- v5 seed: 144개 deco_items (카테고리 2 × 레이어 12 × 6) - schema_v5.sql 적용 후 1회 실행
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z1_0', 'landscape', 'z1', 1, '잔디밭', 'N', 15, '🌱');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z1_1', 'landscape', 'z1', 1, '모래사장', 'N', 15, '🏖️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z1_2', 'landscape', 'z1', 1, '자갈길', 'N', 15, '🪨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z1_3', 'landscape', 'z1', 1, '이끼바닥', 'R', 40, '🍃');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z1_4', 'landscape', 'z1', 1, '낙엽바닥', 'R', 40, '🍂');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z1_5', 'landscape', 'z1', 1, '눈밭', 'SSR', 250, '❄️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z2_0', 'landscape', 'z2', 2, '노을하늘', 'N', 15, '🌇');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z2_1', 'landscape', 'z2', 2, '파스텔하늘', 'N', 15, '🎨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z2_2', 'landscape', 'z2', 2, '별밤하늘', 'N', 15, '🌌');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z2_3', 'landscape', 'z2', 2, '무지개하늘', 'R', 40, '🌈');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z2_4', 'landscape', 'z2', 2, '안개하늘', 'R', 40, '🌫️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z2_5', 'landscape', 'z2', 2, '오로라하늘', 'SSR', 250, '🪐');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z3_0', 'landscape', 'z3', 3, '잔잔한 비', 'N', 15, '🌦️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z3_1', 'landscape', 'z3', 3, '첫눈', 'N', 15, '🌨️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z3_2', 'landscape', 'z3', 3, '벚꽃비', 'N', 15, '🌸');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z3_3', 'landscape', 'z3', 3, '은하수', 'R', 40, '✨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z3_4', 'landscape', 'z3', 3, '반딧불', 'R', 40, '🌟');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z3_5', 'landscape', 'z3', 3, '자욱한 안개', 'SSR', 250, '🌁');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z4_0', 'landscape', 'z4', 4, '산맥 실루엣', 'N', 15, '⛰️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z4_1', 'landscape', 'z4', 4, '등대', 'N', 15, '🗼');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z4_2', 'landscape', 'z4', 4, '풍차', 'N', 15, '🎡');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z4_3', 'landscape', 'z4', 4, '다리', 'R', 40, '🌉');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z4_4', 'landscape', 'z4', 4, '나무숲', 'R', 40, '🌲');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z4_5', 'landscape', 'z4', 4, '섬', 'SSR', 250, '🏝️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z5_0', 'landscape', 'z5', 5, '골든아워 빛', 'N', 15, '🌅');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z5_1', 'landscape', 'z5', 5, '달빛', 'N', 15, '🌕');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z5_2', 'landscape', 'z5', 5, '캠프파이어', 'N', 15, '🔥');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z5_3', 'landscape', 'z5', 5, '가로등', 'R', 40, '💡');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z5_4', 'landscape', 'z5', 5, '오로라 글로우', 'R', 40, '🌠');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z5_5', 'landscape', 'z5', 5, '반짝이는 윤슬', 'SSR', 250, '💫');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z6_0', 'landscape', 'z6', 6, '꽃잎 뿌리기', 'N', 15, '🌸');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z6_1', 'landscape', 'z6', 6, '낙엽 뿌리기', 'N', 15, '🍁');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z6_2', 'landscape', 'z6', 6, '눈송이 뿌리기', 'N', 15, '❄️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z6_3', 'landscape', 'z6', 6, '반짝이 가루', 'R', 40, '✨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z6_4', 'landscape', 'z6', 6, '별가루', 'R', 40, '🌟');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z6_5', 'landscape', 'z6', 6, '이슬방울', 'SSR', 250, '💧');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z7_0', 'landscape', 'z7', 7, '들꽃', 'N', 15, '🌼');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z7_1', 'landscape', 'z7', 7, '벤치', 'N', 15, '🪑');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z7_2', 'landscape', 'z7', 7, '우산', 'N', 15, '☂️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z7_3', 'landscape', 'z7', 7, '자전거', 'R', 40, '🚲');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z7_4', 'landscape', 'z7', 7, '캠핑의자', 'R', 40, '🏕️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z7_5', 'landscape', 'z7', 7, '담요', 'SSR', 250, '🧺');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z8_0', 'landscape', 'z8', 8, '산들바람', 'N', 15, '🍃');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z8_1', 'landscape', 'z8', 8, '물안개', 'N', 15, '🌊');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z8_2', 'landscape', 'z8', 8, '아지랑이', 'N', 15, '🌡️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z8_3', 'landscape', 'z8', 8, '눈보라', 'R', 40, '🌪️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z8_4', 'landscape', 'z8', 8, '불꽃 스파크', 'R', 40, '🔥');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z8_5', 'landscape', 'z8', 8, '반짝임', 'SSR', 250, '✨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z9_0', 'landscape', 'z9', 9, '하트 스티커', 'N', 15, '❤️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z9_1', 'landscape', 'z9', 9, '별 스티커', 'N', 15, '⭐');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z9_2', 'landscape', 'z9', 9, '리본 스티커', 'N', 15, '🎀');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z9_3', 'landscape', 'z9', 9, '무지개 스티커', 'R', 40, '🌈');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z9_4', 'landscape', 'z9', 9, '나비 스티커', 'R', 40, '🦋');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z9_5', 'landscape', 'z9', 9, '새 스티커', 'SSR', 250, '🕊️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z10_0', 'landscape', 'z10', 10, '폴라로이드 프레임', 'N', 15, '🖼️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z10_1', 'landscape', 'z10', 10, '필름 프레임', 'N', 15, '📽️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z10_2', 'landscape', 'z10', 10, '나무 액자', 'N', 15, '🪵');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z10_3', 'landscape', 'z10', 10, '빈티지 액자', 'R', 40, '🕰️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z10_4', 'landscape', 'z10', 10, '네온 액자', 'R', 40, '💡');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z10_5', 'landscape', 'z10', 10, '하트 액자', 'SSR', 250, '💗');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z11_0', 'landscape', 'z11', 11, '오늘도 힐링', 'N', 15, '🍃');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z11_1', 'landscape', 'z11', 11, '여행중', 'N', 15, '✈️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z11_2', 'landscape', 'z11', 11, '고요한 순간', 'N', 15, '🌙');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z11_3', 'landscape', 'z11', 11, '자연 속으로', 'R', 40, '🌳');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z11_4', 'landscape', 'z11', 11, '숨멎 뷰', 'R', 40, '😮');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z11_5', 'landscape', 'z11', 11, '인생샷', 'SSR', 250, '📸');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z12_0', 'landscape', 'z12', 12, '반짝이 입자', 'N', 15, '✨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z12_1', 'landscape', 'z12', 12, '꽃가루', 'N', 15, '🌸');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z12_2', 'landscape', 'z12', 12, '눈가루', 'N', 15, '❄️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z12_3', 'landscape', 'z12', 12, '별빛 입자', 'R', 40, '🌟');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z12_4', 'landscape', 'z12', 12, '빛망울', 'R', 40, '🔆');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_landscape_z12_5', 'landscape', 'z12', 12, '불티', 'SSR', 250, '🔥');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z1_0', 'food', 'z1', 1, '체크무늬 식탁보', 'N', 15, '🏁');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z1_1', 'food', 'z1', 1, '우드 트레이', 'N', 15, '🪵');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z1_2', 'food', 'z1', 1, '대리석 판', 'N', 15, '⬜');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z1_3', 'food', 'z1', 1, '리넨 매트', 'R', 40, '🧵');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z1_4', 'food', 'z1', 1, '크래프트지', 'R', 40, '📜');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z1_5', 'food', 'z1', 1, '파스텔 매트', 'SR', 100, '🎨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z2_0', 'food', 'z2', 2, '따뜻한 조명', 'N', 15, '💡');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z2_1', 'food', 'z2', 2, '카페 무드 조명', 'N', 15, '☕');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z2_2', 'food', 'z2', 2, '화사한 자연광', 'N', 15, '☀️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z2_3', 'food', 'z2', 2, '몽환 필터', 'R', 40, '🌫️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z2_4', 'food', 'z2', 2, '필름 감성', 'R', 40, '📷');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z2_5', 'food', 'z2', 2, '골든 라이트', 'SR', 100, '✨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z3_0', 'food', 'z3', 3, '김 모락모락', 'N', 15, '💨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z3_1', 'food', 'z3', 3, '브런치 무드', 'N', 15, '🥐');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z3_2', 'food', 'z3', 3, '디저트 타임', 'N', 15, '🍰');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z3_3', 'food', 'z3', 3, '홈카페 무드', 'R', 40, '🏠');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z3_4', 'food', 'z3', 3, '피크닉 무드', 'R', 40, '🧺');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z3_5', 'food', 'z3', 3, '애프터눈티', 'SR', 100, '🫖');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z4_0', 'food', 'z4', 4, '화병', 'N', 15, '🌷');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z4_1', 'food', 'z4', 4, '커튼', 'N', 15, '🪟');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z4_2', 'food', 'z4', 4, '창가풍경', 'N', 15, '🌤️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z4_3', 'food', 'z4', 4, '책', 'R', 40, '📖');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z4_4', 'food', 'z4', 4, '캔들', 'R', 40, '🕯️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z4_5', 'food', 'z4', 4, '소품 그릇', 'SR', 100, '🥣');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z5_0', 'food', 'z5', 5, '반짝이는 시럽', 'N', 15, '🍯');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z5_1', 'food', 'z5', 5, '캔들 불빛', 'N', 15, '🕯️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z5_2', 'food', 'z5', 5, '크리미 하이라이트', 'N', 15, '🥛');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z5_3', 'food', 'z5', 5, '카라멜 글로우', 'R', 40, '🍮');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z5_4', 'food', 'z5', 5, '초콜릿 드리즐 광', 'R', 40, '🍫');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z5_5', 'food', 'z5', 5, '라떼아트 광', 'SR', 100, '☕');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z6_0', 'food', 'z6', 6, '딸기 토핑', 'N', 15, '🍓');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z6_1', 'food', 'z6', 6, '초코칩 스프링클', 'N', 15, '🍫');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z6_2', 'food', 'z6', 6, '민트잎', 'N', 15, '🌿');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z6_3', 'food', 'z6', 6, '크림 스월', 'R', 40, '🍦');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z6_4', 'food', 'z6', 6, '견과류 크런치', 'R', 40, '🥜');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z6_5', 'food', 'z6', 6, '슈가파우더', 'SR', 100, '🍬');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z7_0', 'food', 'z7', 7, '포크&나이프', 'N', 15, '🍴');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z7_1', 'food', 'z7', 7, '냅킨', 'N', 15, '🧻');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z7_2', 'food', 'z7', 7, '빨대', 'N', 15, '🥤');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z7_3', 'food', 'z7', 7, '티스푼', 'R', 40, '🥄');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z7_4', 'food', 'z7', 7, '원두', 'R', 40, '☕');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z7_5', 'food', 'z7', 7, '꽃장식', 'SR', 100, '💐');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z8_0', 'food', 'z8', 8, '김 모락모락', 'N', 15, '💨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z8_1', 'food', 'z8', 8, '버터 녹는 광', 'N', 15, '🧈');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z8_2', 'food', 'z8', 8, '탄산 기포', 'N', 15, '🫧');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z8_3', 'food', 'z8', 8, '시럽 흘러내림', 'R', 40, '🍯');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z8_4', 'food', 'z8', 8, '설탕 반짝임', 'R', 40, '✨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z8_5', 'food', 'z8', 8, '스팀 웨이브', 'SR', 100, '♨️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z9_0', 'food', 'z9', 9, '냠냠 스티커', 'N', 15, '😋');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z9_1', 'food', 'z9', 9, '맛있닭 스티커', 'N', 15, '🍗');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z9_2', 'food', 'z9', 9, '딸기 스티커', 'N', 15, '🍓');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z9_3', 'food', 'z9', 9, '하트 스티커', 'R', 40, '❤️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z9_4', 'food', 'z9', 9, '별사탕 스티커', 'R', 40, '⭐');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z9_5', 'food', 'z9', 9, '리본 스티커', 'SR', 100, '🎀');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z10_0', 'food', 'z10', 10, '폴라로이드 프레임', 'N', 15, '🖼️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z10_1', 'food', 'z10', 10, '우드 액자', 'N', 15, '🪵');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z10_2', 'food', 'z10', 10, '파스텔 액자', 'N', 15, '🎨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z10_3', 'food', 'z10', 10, '빈티지 메뉴판 프레임', 'R', 40, '📋');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z10_4', 'food', 'z10', 10, '네온 프레임', 'R', 40, '💡');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z10_5', 'food', 'z10', 10, '리본 프레임', 'SR', 100, '🎀');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z11_0', 'food', 'z11', 11, '오늘의 한 끼', 'N', 15, '🍽️');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z11_1', 'food', 'z11', 11, '냠냠타임', 'N', 15, '😋');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z11_2', 'food', 'z11', 11, '소소한 행복', 'N', 15, '🌼');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z11_3', 'food', 'z11', 11, '먹스타그램', 'R', 40, '📸');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z11_4', 'food', 'z11', 11, '홈카페', 'R', 40, '☕');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z11_5', 'food', 'z11', 11, '디저트는 사랑', 'SR', 100, '🍰');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z12_0', 'food', 'z12', 12, '슈가파우더 입자', 'N', 15, '🍬');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z12_1', 'food', 'z12', 12, '스프링클 입자', 'N', 15, '🎊');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z12_2', 'food', 'z12', 12, '크럼블 조각', 'N', 15, '🍪');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z12_3', 'food', 'z12', 12, '반짝이 가루', 'R', 40, '✨');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z12_4', 'food', 'z12', 12, '버블 입자', 'R', 40, '🫧');
INSERT INTO deco_items (id, category, part, z_index, name, rarity, price, emoji) VALUES ('deco_food_z12_5', 'food', 'z12', 12, '김 입자', 'SR', 100, '💨');
