-- 루트카드 스킨 아이템 144개 (12파츠 x 12개: N x5@5, R x4@15, SR x2@30, SSR x1@80)
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_0', 'card_bg', '민트 단색 배경', 'N', 5, '🟩');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_1', 'card_bg', '라벤더 단색 배경', 'N', 5, '🟪');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_2', 'card_bg', '크림 단색 배경', 'N', 5, '🟨');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_3', 'card_bg', '하늘색 단색 배경', 'N', 5, '🟦');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_4', 'card_bg', '베이지 단색 배경', 'N', 5, '🟫');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_5', 'card_bg', 'kyungyu의 딸기우유 노을 배경', 'R', 15, '🍓');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_6', 'card_bg', '체크패턴 배경', 'R', 15, '🏁');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_7', 'card_bg', '뭉게구름 배경', 'R', 15, '☁️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_8', 'card_bg', '별사탕 가게 유리질감', 'R', 15, '🍬');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_9', 'card_bg', '노을 그라데이션', 'SR', 30, '🌇');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_10', 'card_bg', '야경 그라데이션', 'SR', 30, '🌃');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_card_bg_11', 'card_bg', 'kyungyu의 무지개 오로라 배경', 'SSR', 80, '🌈');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_0', 'map_style', '기본 지도', 'N', 5, '🗺️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_1', 'map_style', '심플 그레이 지도', 'N', 5, '⬜');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_2', 'map_style', '파스텔 지도', 'N', 5, '🎨');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_3', 'map_style', '라인 지도', 'N', 5, '📐');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_4', 'map_style', '화이트 지도', 'N', 5, '⚪');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_5', 'map_style', '크림색 종이 지도', 'R', 15, '📜');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_6', 'map_style', '다크모드 지도', 'R', 15, '🌑');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_7', 'map_style', '빈티지 지도', 'R', 15, '🧭');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_8', 'map_style', '청록 지도', 'R', 15, '🌊');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_9', 'map_style', '수채화 지도', 'SR', 30, '🖌️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_10', 'map_style', '네온 지도', 'SR', 30, '💡');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_map_style_11', 'map_style', 'kyungyu의 별밤 지도', 'SSR', 80, '🌌');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_0', 'route_line', '기본 실선', 'N', 5, '➖');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_1', 'route_line', '얇은 점선', 'N', 5, '┄');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_2', 'route_line', '두꺼운 실선', 'N', 5, '▬');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_3', 'route_line', '회색 점선', 'N', 5, '⋯');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_4', 'route_line', '곡선 화살표', 'N', 5, '➰');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_5', 'route_line', '별사탕 도트선', 'R', 15, '⭐');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_6', 'route_line', '하트 점선', 'R', 15, '💗');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_7', 'route_line', '리본 선', 'R', 15, '🎀');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_8', 'route_line', '발자국 선', 'R', 15, '👣');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_9', 'route_line', '무지개 선', 'SR', 30, '🌈');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_10', 'route_line', '네온 글로우 선', 'SR', 30, '🟣');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_route_line_11', 'route_line', 'kyungyu의 별똥별 선', 'SSR', 80, '☄️');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_0', 'pin_start', '기본 깃발', 'N', 5, '🚩');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_1', 'pin_start', '초록 핀', 'N', 5, '📍');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_2', 'pin_start', '파랑 핀', 'N', 5, '🔵');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_3', 'pin_start', '동그라미 핀', 'N', 5, '⚪');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_4', 'pin_start', '별 핀', 'N', 5, '⭐');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_5', 'pin_start', '곰돌이 핀', 'R', 15, '🐻');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_6', 'pin_start', '별사탕 핀', 'R', 15, '🍬');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_7', 'pin_start', '리본 깃발', 'R', 15, '🎏');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_8', 'pin_start', '왕관 미니', 'R', 15, '👑');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_9', 'pin_start', '반짝이는 왕관', 'SR', 30, '✨');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_10', 'pin_start', '황금 별', 'SR', 30, '🌟');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_start_11', 'pin_start', 'kyungyu 시그니처 곰돌이 왕관', 'SSR', 80, '🐻');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_0', 'pin_via', '기본 점', 'N', 5, '⚫');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_1', 'pin_via', '회색 점', 'N', 5, '⚪');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_2', 'pin_via', '파랑 점', 'N', 5, '🔵');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_3', 'pin_via', '숫자 핀', 'N', 5, '🔢');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_4', 'pin_via', '동그라미', 'N', 5, '⭕');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_5', 'pin_via', '커피잔', 'R', 15, '☕');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_6', 'pin_via', '하트', 'R', 15, '❤️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_7', 'pin_via', '케이크', 'R', 15, '🍰');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_8', 'pin_via', '별', 'R', 15, '⭐');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_9', 'pin_via', '반짝이는 하트', 'SR', 30, '💖');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_10', 'pin_via', '무지개 별', 'SR', 30, '🌟');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_via_11', 'pin_via', 'kyungyu의 딸기 케이크', 'SSR', 80, '🍓');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_0', 'pin_end', '기본 체크', 'N', 5, '✅');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_1', 'pin_end', '빨강 핀', 'N', 5, '📍');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_2', 'pin_end', '깃발', 'N', 5, '🏁');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_3', 'pin_end', '별 핀', 'N', 5, '⭐');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_4', 'pin_end', '하트 핀', 'N', 5, '💗');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_5', 'pin_end', '집', 'R', 15, '🏠');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_6', 'pin_end', '보물상자', 'R', 15, '📦');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_7', 'pin_end', '하트풍선', 'R', 15, '🎈');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_8', 'pin_end', '트로피', 'R', 15, '🏆');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_9', 'pin_end', '황금 보물상자', 'SR', 30, '💰');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_10', 'pin_end', '반짝이는 하트풍선', 'SR', 30, '💝');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_pin_end_11', 'pin_end', 'JMT 도착 보물상자', 'SSR', 80, '📦');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_0', 'title_badge', '기본체', 'N', 5, '🔤');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_1', 'title_badge', '굵은체', 'N', 5, '🔠');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_2', 'title_badge', '손글씨체', 'N', 5, '✍️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_3', 'title_badge', '라운드체', 'N', 5, '🔵');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_4', 'title_badge', '심플 스탬프', 'N', 5, '🔖');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_5', 'title_badge', 'JMT 스탬프', 'R', 15, '🍽️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_6', 'title_badge', '인생루트 스탬프', 'R', 15, '🏅');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_7', 'title_badge', '리본 폰트', 'R', 15, '🎀');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_8', 'title_badge', '네온 폰트', 'R', 15, '💡');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_9', 'title_badge', 'kyungyu''s pick 스탬프', 'SR', 30, '⭐');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_10', 'title_badge', '금박 폰트', 'SR', 30, '🥇');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_title_badge_11', 'title_badge', 'kyungyu 시그니처 홀로그램 뱃지', 'SSR', 80, '💎');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_0', 'author_badge', '기본 별', 'N', 5, '⭐');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_1', 'author_badge', '초록 잎', 'N', 5, '🍃');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_2', 'author_badge', '파랑 방울', 'N', 5, '💧');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_3', 'author_badge', '하트', 'N', 5, '❤️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_4', 'author_badge', '동그라미', 'N', 5, '⚪');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_5', 'author_badge', '별사탕 요정', 'R', 15, '🧚');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_6', 'author_badge', '미니 왕관', 'R', 15, '👑');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_7', 'author_badge', '레벨 뱃지', 'R', 15, '🎖️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_8', 'author_badge', '리본', 'R', 15, '🎀');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_9', 'author_badge', '반짝이는 왕관', 'SR', 30, '✨');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_10', 'author_badge', '골드 레벨 뱃지', 'SR', 30, '🥇');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_author_badge_11', 'author_badge', 'kyungyu 마스터 요정', 'SSR', 80, '🧚‍♀️');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_0', 'weather_effect', '맑음', 'N', 5, '☀️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_1', 'weather_effect', '살짝 흐림', 'N', 5, '🌤️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_2', 'weather_effect', '옅은 안개', 'N', 5, '🌫️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_3', 'weather_effect', '산들바람', 'N', 5, '🍃');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_4', 'weather_effect', '은은한 빛', 'N', 5, '✨');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_5', 'weather_effect', '눈 내림', 'R', 15, '❄️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_6', 'weather_effect', '꽃가루', 'R', 15, '🌸');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_7', 'weather_effect', '햇살', 'R', 15, '🌞');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_8', 'weather_effect', '비', 'R', 15, '🌧️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_9', 'weather_effect', '벚꽃 흩날림', 'SR', 30, '🌸');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_10', 'weather_effect', '별가루', 'SR', 30, '✨');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_weather_effect_11', 'weather_effect', 'kyungyu의 오로라 커튼', 'SSR', 80, '🌌');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_0', 'frame', '심플 라인', 'N', 5, '▭');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_1', 'frame', '라운드 라인', 'N', 5, '⬜');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_2', 'frame', '점선 테두리', 'N', 5, '⬚');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_3', 'frame', '이중선', 'N', 5, '═');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_4', 'frame', '그림자 테두리', 'N', 5, '🔲');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_5', 'frame', '곰돌이 액자', 'R', 15, '🐻');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_6', 'frame', '필름 테두리', 'R', 15, '🎞️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_7', 'frame', '리본 테두리', 'R', 15, '🎀');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_8', 'frame', '나무 액자', 'R', 15, '🪵');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_9', 'frame', '별사탕 자판기 프레임', 'SR', 30, '🍬');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_10', 'frame', '골드 프레임', 'SR', 30, '🖼️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_frame_11', 'frame', 'kyungyu의 찢어진 편지지 프레임', 'SSR', 80, '💌');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_0', 'sticker', '작은 별', 'N', 5, '⭐');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_1', 'sticker', '하트', 'N', 5, '❤️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_2', 'sticker', '구름', 'N', 5, '☁️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_3', 'sticker', '잎사귀', 'N', 5, '🍃');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_4', 'sticker', '동그란 점', 'N', 5, '⚪');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_5', 'sticker', 'healing 문구', 'R', 15, '🧘');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_6', 'sticker', '고양이', 'R', 15, '🐱');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_7', 'sticker', '뭉게구름', 'R', 15, '☁️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_8', 'sticker', '리본 스티커', 'R', 15, '🎀');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_9', 'sticker', '반짝이는 3D 하트', 'SR', 30, '💖');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_10', 'sticker', '무지개 스티커', 'SR', 30, '🌈');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_sticker_11', 'sticker', 'kyungyu의 시그니처 곰돌이 스티커', 'SSR', 80, '🐻');

INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_0', 'filter_aura', '살짝 밝게', 'N', 5, '🔆');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_1', 'filter_aura', '살짝 따뜻하게', 'N', 5, '🌤️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_2', 'filter_aura', '살짝 시원하게', 'N', 5, '🧊');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_3', 'filter_aura', '부드럽게', 'N', 5, '🩵');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_4', 'filter_aura', '선명하게', 'N', 5, '🔍');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_5', 'filter_aura', '필름 노이즈', 'R', 15, '🎞️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_6', 'filter_aura', '은은한 후광', 'R', 15, '🕯️');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_7', 'filter_aura', '빛망울', 'R', 15, '✨');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_8', 'filter_aura', '그레인', 'R', 15, '🌾');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_9', 'filter_aura', '글리터 파티클', 'SR', 30, '✨');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_10', 'filter_aura', '무지개 후광', 'SR', 30, '🌈');
INSERT INTO route_skin_items (id, part, name, rarity, price, emoji) VALUES ('rskin_filter_aura_11', 'filter_aura', 'kyungyu의 홀로그램 오라', 'SSR', 80, '💎');
